# Generated by Django 4.2.25 on 2025-10-17 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_team', models.CharField(max_length=128)),
                ('defense_team', models.CharField(max_length=128)),
                ('inning', models.PositiveSmallIntegerField(default=1)),
                ('half_inning', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom')], default='top', max_length=6)),
                ('outs', models.PositiveSmallIntegerField(help_text='Number of outs before the play.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('balls', models.PositiveSmallIntegerField(help_text='Ball count before the play.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('strikes', models.PositiveSmallIntegerField(help_text='Strike count before the play.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('runners_on_first', models.BooleanField(default=False)),
                ('runners_on_second', models.BooleanField(default=False)),
                ('runners_on_third', models.BooleanField(default=False)),
                ('score_difference', models.IntegerField(default=0, help_text='Offense score minus defense score before the play.')),
                ('context_notes', models.TextField(blank=True)),
                ('recommended_pitch', models.CharField(blank=True, max_length=128)),
                ('defensive_alignment', models.JSONField(blank=True, default=dict)),
                ('catcher_instructions', models.TextField(blank=True)),
                ('offensive_sign', models.TextField(blank=True)),
                ('runner_instructions', models.TextField(blank=True)),
                ('actual_outcome', models.TextField(blank=True)),
                ('generated_from_engine', models.BooleanField(default=False, help_text='True when this record was created from the recommendation engine.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
